name=DIYables TFT Touch Shield
version=2.2.1
author=DIYables.io
maintainer=DIYables.io (diyables.io@gmail.com)
sentence=The Arduino library for the DIYables 320x480, 3.5-inch Color TFT LCD Display Shield (with Touch). Compatible with hardware platforms that follow the Uno/Mega form factor, including Arduino Uno R3, Uno R4 WiFi/Minima, Mega, and Giga.
paragraph=This library is designed for use with the 3.5-inch Color TFT LCD Touch Display Shield on Arduino boards such as the Uno R3, Uno R4 WiFi/Minima, Mega, Giga, and other compatible models.
category=Display
url=https://diyables.io/tft-touch-shield
architectures=*
depends=Adafruit GFX Library
